export const SERVICE_CREATE_REQUEST = '@/SERVICE/CREATE/REQUEST'
export const SERVICE_CREATE_RESPONSE = '@/SERVICE/CREATE/RESPONSE'
export const SERVICE_CREATE_RESPONSE_FAIL = '@/SERVICE/CREATE/RESPONSE_FAIL'
