export const CREATE_SERVICE_REQUEST = '@/CREATE_SERVICE/REQUEST'
export const CREATE_SERVICE_RESPONSE = '@/CREATE_SERVICE/RESPONSE'
export const CREATE_SERVICE_RESPONSE_FAIL = '@/CREATE_SERVICE/RESPONSE_FAIL'
