export const SERVICES_REQUEST = '@/SERVICES/REQUEST'
export const SERVICES_RESPONSE = '@/SERVICES/RESPONSE'
export const SERVICES_RESPONSE_FAIL = '@/SERVICES/RESPONSE_FAIL'

export const SERVICES_CHANGE_FILTERS = '@/SERVICES/CHANGE_FILTERS'
