export const SERVICE_TYPES_REQUEST = '@/SERVICE_TYPES/REQUEST'
export const SERVICE_TYPES_RESPONSE = '@/SERVICE_TYPES/RESPONSE'
export const SERVICE_TYPES_RESPONSE_FAIL = '@/SERVICE_TYPES/RESPONSE_FAIL'
